### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by bowu678** [a4demon/waf_identify#1]
python: can't open file 'main.py': [Errno 2] No such file or directory

main.py to waf.py

but:
Traceback (most recent call last):
  File "waf.py", line 101, in <module>
    wafidentify.run()
  File "waf.py", line 64, in run
    self.info = "payload：{}，状态码：{}!!!".format(add_url, resp.status_code)
NameError: global name 'add_url' is not defined

**Comment by 7z1** [comment]
已修复，谢谢提醒

**Comment by 7z1** [comment]
> python: can't open file 'main.py': [Errno 2] No such file or directory
> 
> main.py to waf.py
> 
> but:
> Traceback (most recent call last):
> File "waf.py", line 101, in 
> wafidentify.run()
> File "waf.py", line 64, in run
> self.info = "payload：{}，状态码：{}!!!".format(add_url, resp.status_code)
> NameError: global name 'add_url' is not defined

已修复，谢谢提醒
